import type { Entry } from '../types'

export type ButtonStyle = 'soft' | 'glossy' | 'sharp' | 'retro' | 'ornate' | 'outline' | 'bubbly' | 'neon' | 'pixel' | 'chrome' | 'paper' | 'clay' | 'glass' | 'neu' | 'holo'
export type LayoutFamily = 'classic' | 'floating' | 'top-tabs' | 'rail' | 'grid' | 'framed' | 'centered' | 'zine' | 'window' | 'terminal' | 'magazine' | 'bubble'
export type IconStyle = 'line' | 'bold' | 'pixel' | 'hand' | 'duotone' | 'ornate' | 'bubbly' | 'chrome' | 'neon' | 'geometric'
export type MotionStyle = 'smooth' | 'bouncy' | 'snappy' | 'glitch' | 'float' | 'stepped' | 'elegant' | 'wobble'

export interface ThemeColours {
  bg: string
  surface: string
  surface2: string
  line: string
  text: string
  muted: string
  accent: string
  onAccent: string
  accentText: string
  accentSoft: string
  /** glossy buttons: highlight and shade of the accent, both still readable under onAccent */
  accentHi: string
  accentLo: string
  good: string
  goodSoft: string
  bad: string
  badSoft: string
  gold: string
}

/** Generated by scripts/make-themes.mjs from the aesthetic's Pinterest board. */
export interface Theme {
  id: string
  dark: boolean
  font: string
  body: string
  buttons: ButtonStyle
  layout: LayoutFamily
  icons: IconStyle
  motion: MotionStyle
  pattern: string
  caps: boolean
  /** number of published pins in public/pins/<id>/ */
  pins: number
  colours: ThemeColours
  swatches: string[]
  glow: string
}

const two = (n: number) => String(n).padStart(2, '0')

/** A theme's n-th pin (1-based), wrapping around. */
export const pinUrl = (theme: Pick<Theme, 'id' | 'pins'>, n: number) =>
  `${import.meta.env.BASE_URL}pins/${theme.id}/${two(((n - 1) % Math.max(theme.pins, 1)) + 1)}.webp`

export const pinThumb = (id: string) => `${import.meta.env.BASE_URL}pins/${id}/thumb.webp`

export type Themes = Record<string, Theme>

// Display fonts differ a lot in width; the scale keeps headings on screen.
const DISPLAY: Record<string, { fallback: string; scale: number }> = {
  'Instrument Serif': { fallback: 'Georgia, serif', scale: 1 },
  Limelight: { fallback: 'Georgia, serif', scale: 0.82 },
  'Poiret One': { fallback: 'system-ui, sans-serif', scale: 0.95 },
  'Playfair Display': { fallback: 'Georgia, serif', scale: 0.88 },
  'Cormorant Garamond': { fallback: 'Georgia, serif', scale: 1.02 },
  Cinzel: { fallback: 'Georgia, serif', scale: 0.78 },
  Silkscreen: { fallback: 'monospace', scale: 0.6 },
  VT323: { fallback: 'monospace', scale: 1.1 },
  Orbitron: { fallback: 'system-ui, sans-serif', scale: 0.7 },
  Audiowide: { fallback: 'system-ui, sans-serif', scale: 0.78 },
  Fredoka: { fallback: 'system-ui, sans-serif', scale: 0.88 },
  'Baloo 2': { fallback: 'system-ui, sans-serif', scale: 0.92 },
  Pacifico: { fallback: 'cursive', scale: 0.82 },
  Shrikhand: { fallback: 'Georgia, serif', scale: 0.8 },
  Righteous: { fallback: 'system-ui, sans-serif', scale: 0.88 },
  Bungee: { fallback: 'system-ui, sans-serif', scale: 0.68 },
  'Rubik Mono One': { fallback: 'monospace', scale: 0.56 },
  'Special Elite': { fallback: 'monospace', scale: 0.82 },
  'Space Grotesk': { fallback: 'system-ui, sans-serif', scale: 0.86 },
  'Archivo Black': { fallback: 'system-ui, sans-serif', scale: 0.74 },
  Syne: { fallback: 'system-ui, sans-serif', scale: 0.82 },
  'DM Serif Display': { fallback: 'Georgia, serif', scale: 0.92 },
  'Pirata One': { fallback: 'Georgia, serif', scale: 1 },
  Caveat: { fallback: 'cursive', scale: 1.1 },
  Lobster: { fallback: 'cursive', scale: 0.92 },
  Monoton: { fallback: 'system-ui, sans-serif', scale: 0.66 },
  'Tilt Neon': { fallback: 'system-ui, sans-serif', scale: 0.88 },
  'Bowlby One SC': { fallback: 'system-ui, sans-serif', scale: 0.68 },
  'Permanent Marker': { fallback: 'cursive', scale: 0.84 },
  Chewy: { fallback: 'system-ui, sans-serif', scale: 0.92 },
  'ZCOOL XiaoWei': { fallback: 'Georgia, serif', scale: 0.92 },
  'Abril Fatface': { fallback: 'Georgia, serif', scale: 0.86 },
  'Alfa Slab One': { fallback: 'Georgia, serif', scale: 0.76 },
  Fraunces: { fallback: 'Georgia, serif', scale: 0.9 },
  Comfortaa: { fallback: 'system-ui, sans-serif', scale: 0.82 },
  Michroma: { fallback: 'system-ui, sans-serif', scale: 0.6 },
  Unbounded: { fallback: 'system-ui, sans-serif', scale: 0.7 },
}

const BODY: Record<string, string> = {
  system: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  Lora: "'Lora', Georgia, serif",
  Nunito: "'Nunito', system-ui, sans-serif",
  'Work Sans': "'Work Sans', system-ui, sans-serif",
  'IBM Plex Mono': "'IBM Plex Mono', ui-monospace, monospace",
}

const VARS: Record<keyof ThemeColours, string> = {
  bg: '--bg',
  surface: '--surface',
  surface2: '--surface-2',
  line: '--line',
  text: '--text',
  muted: '--muted',
  accent: '--accent',
  onAccent: '--on-accent',
  accentText: '--accent-text',
  accentSoft: '--accent-soft',
  accentHi: '--accent-hi',
  accentLo: '--accent-lo',
  good: '--good',
  goodSoft: '--good-soft',
  bad: '--bad',
  badSoft: '--bad-soft',
  gold: '--gold',
}

const EXTRA = ['--font', '--font-display', '--display-scale', '--glow', '--shadow', '--veil']

/**
 * Ornamental display faces (script, blackletter, grunge, inline). They stay on
 * big titles and numbers; quiz prompts and lesson headings use the body face.
 */
const DECORATIVE = new Set([
  'Bungee Inline', 'Bungee Shade', 'Creepster', 'Dancing Script', 'Great Vibes', 'Kaushan Script', 'Long Cang', 'Ma Shan Zheng',
  'MedievalSharp', 'Metal Mania', 'Monoton', 'Pacifico', 'Pirata One', 'Rock Salt', 'Rubik Dirt', 'Rubik Glitch',
  'Rubik Spray Paint', 'Saira Stencil One', 'Sancreek', 'Satisfy', 'Uncial Antiqua', 'UnifrakturMaguntia',
])

/** A lesson's theme unlocks when it's learned, and stays unlocked. */
export const themeUnlocked = (e: Entry | undefined) => e?.u === 1 || (e?.lt ?? 0) >= 2

function fontsUrl(theme: Theme) {
  const families = [`family=${encodeURIComponent(theme.font).replace(/%20/g, '+')}`]
  if (theme.body !== 'system') families.push(`family=${encodeURIComponent(theme.body).replace(/%20/g, '+')}:wght@400;600;700`)
  return `https://fonts.googleapis.com/css2?${families.join('&')}&display=swap`
}

/**
 * Applies a theme to the whole app, or restores the default look (null).
 * `root` can be another document's root, e.g. the intro's frame.
 */
export function applyTheme(theme: Theme | null, root: HTMLElement = document.documentElement) {
  const doc = root.ownerDocument
  for (const v of [...Object.values(VARS), ...EXTRA]) root.style.removeProperty(v)
  for (const key of ['buttons', 'layout', 'icons', 'motion', 'pattern', 'caps', 'deco', 'theme']) delete root.dataset[key]
  root.style.removeProperty('color-scheme')
  doc.getElementById('theme-fonts')?.remove()
  const meta = doc.querySelectorAll<HTMLMetaElement>('meta[name="theme-color"]')

  if (!theme) {
    meta.forEach((m) => (m.content = m.media.includes('dark') ? '#141216' : '#f5f1ea'))
    return
  }

  for (const [key, v] of Object.entries(VARS)) root.style.setProperty(v, theme.colours[key as keyof ThemeColours])
  const display = DISPLAY[theme.font] ?? { fallback: 'system-ui, sans-serif', scale: 0.86 }
  root.style.setProperty('--font-display', `'${theme.font}', ${display.fallback}`)
  root.style.setProperty('--display-scale', String(display.scale))
  root.style.setProperty('--font', BODY[theme.body] ?? BODY.system)
  root.style.setProperty('--glow', theme.glow)
  // How much of the background colour lies over the collage.
  root.style.setProperty('--veil', theme.dark ? '72%' : '64%')
  if (theme.dark) root.style.setProperty('--shadow', 'none')
  root.style.setProperty('color-scheme', theme.dark ? 'dark' : 'light')
  root.dataset.buttons = theme.buttons
  root.dataset.layout = theme.layout
  root.dataset.icons = theme.icons
  root.dataset.motion = theme.motion
  root.dataset.pattern = theme.pattern
  if (theme.caps) root.dataset.caps = ''
  if (DECORATIVE.has(theme.font)) root.dataset.deco = ''
  root.dataset.theme = theme.id
  meta.forEach((m) => (m.content = theme.colours.bg))

  const link = doc.createElement('link')
  link.id = 'theme-fonts'
  link.rel = 'stylesheet'
  link.href = fontsUrl(theme)
  doc.head.appendChild(link)
}
