// One hand-made design per aesthetic, from studying its Pinterest board
// (pinterest/<Aesthetic>/, local only). Colours come from the pins themselves;
// these pick everything else. The families are defined in src/index.css and
// src/components/Icon.tsx:
//   buttons: soft glossy sharp retro ornate outline bubbly neon pixel chrome paper clay glass neu holo
//   layout:  classic floating top-tabs rail grid framed centered zine window terminal magazine bubble
//   icons:   line bold pixel hand duotone ornate bubbly chrome neon geometric
//   motion:  smooth bouncy snappy glitch float stepped elegant wobble
//   pattern: see [data-pattern] in src/index.css
// font is a Google Font (display only); body is one of system, Lora, Nunito, Work Sans, IBM Plex Mono.
// accent is the board's signature colour; caps sets headings in capitals;
// paper keeps the background untinted for black-ink-on-paper boards.

export const DESIGNS = {
  '2000s-modern-baroque': { font: 'Yeseva One', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'elegant', pattern: 'damask', dark: true, accent: '#c9a24a' },
  '2010s-meme-maximalism': { font: 'Anton', body: 'system', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'wobble', pattern: 'stars', dark: true, accent: '#ff3fd0', caps: true },
  '8-bit': { font: 'Press Start 2P', body: 'IBM Plex Mono', buttons: 'pixel', layout: 'framed', icons: 'pixel', motion: 'stepped', pattern: 'scanlines', dark: true, accent: '#e4301e' },
  '80s-90s-afrocentrism': { font: 'Lilita One', body: 'Nunito', buttons: 'retro', layout: 'grid', icons: 'geometric', motion: 'bouncy', pattern: 'zigzag', dark: false, accent: '#1f8a3b' },
  'acid-design': { font: 'Unbounded', body: 'Work Sans', buttons: 'neon', layout: 'magazine', icons: 'neon', motion: 'glitch', pattern: 'grid', dark: true, accent: '#b6ff3b', caps: true },
  'american-kitsch': { font: 'Lobster', body: 'Nunito', buttons: 'retro', layout: 'floating', icons: 'bold', motion: 'bouncy', pattern: 'checker', dark: false, accent: '#e23b3b' },
  'art-deco': { font: 'Limelight', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'elegant', pattern: 'fans', dark: true, accent: '#d4af37', caps: true },
  'art-nouveau': { font: 'Cormorant Garamond', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'waves', dark: false, accent: '#7b8f45' },
  'arts-and-crafts': { font: 'Alegreya SC', body: 'Lora', buttons: 'outline', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'damask', dark: false, accent: '#a33a2a' },
  'atomic-age': { font: 'Righteous', body: 'Nunito', buttons: 'retro', layout: 'floating', icons: 'geometric', motion: 'bouncy', pattern: 'stars', dark: false, accent: '#1f9e9a' },
  austurbane: { font: 'Fraunces', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'smooth', pattern: 'grain', dark: false, accent: '#c48a7a' },
  'avant-basic': { font: 'Fraunces', body: 'Nunito', buttons: 'bubbly', layout: 'grid', icons: 'bubbly', motion: 'bouncy', pattern: 'checker', dark: false },
  avantropop: { font: 'Unbounded', body: 'system', buttons: 'glossy', layout: 'zine', icons: 'bold', motion: 'glitch', pattern: 'halftone', dark: true, accent: '#ff2fa8', caps: true },
  baroque: { font: 'Playfair Display', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'damask', dark: false, accent: '#b8892a' },
  biedermeier: { font: 'Cormorant Garamond', body: 'Lora', buttons: 'outline', layout: 'classic', icons: 'line', motion: 'smooth', pattern: 'stripes', dark: false, accent: '#3c6e5d' },
  'big-pop': { font: 'Abril Fatface', body: 'Work Sans', buttons: 'sharp', layout: 'magazine', icons: 'bold', motion: 'snappy', pattern: 'halftone', dark: false, accent: '#e3262b', caps: true },
  'blob-world': { font: 'Bagel Fat One', body: 'Nunito', buttons: 'bubbly', layout: 'bubble', icons: 'bubbly', motion: 'float', pattern: 'bubbles', dark: false },
  'bootleg-aesthetic': { font: 'Bowlby One SC', body: 'system', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'wobble', pattern: 'stars', dark: false, accent: '#e0242b', caps: true },
  'bootleg-mixtape': { font: 'Bungee Shade', body: 'system', buttons: 'chrome', layout: 'zine', icons: 'bold', motion: 'snappy', pattern: 'rays', dark: true, accent: '#ff6a00', caps: true },
  'bright-tertiaries': { font: 'Lilita One', body: 'Nunito', buttons: 'soft', layout: 'grid', icons: 'bubbly', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#1e9e8f' },
  'british-countryside': { font: 'Playfair Display', body: 'Lora', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'smooth', pattern: 'grain', dark: false, accent: '#3f5f45' },
  'candy-sleaze': { font: 'Pacifico', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'bubbly', motion: 'bouncy', pattern: 'sparkles', dark: false, accent: '#ff4fa8' },
  'carson-dellosa-art-style': { font: 'Grandstander', body: 'Nunito', buttons: 'retro', layout: 'grid', icons: 'bold', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#2d6cdf' },
  'catholic-kitsch': { font: 'UnifrakturMaguntia', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'float', pattern: 'damask', dark: true, accent: '#ff3fb4' },
  chicha: { font: 'Bungee', body: 'system', buttons: 'neon', layout: 'zine', icons: 'neon', motion: 'bouncy', pattern: 'rays', dark: true, accent: '#ff2fa0', caps: true },
  chromecore: { font: 'Krona One', body: 'system', buttons: 'chrome', layout: 'classic', icons: 'chrome', motion: 'float', pattern: 'grid', dark: false, accent: '#6f8fc8', caps: true },
  claymorphism: { font: 'Fredoka', body: 'Nunito', buttons: 'clay', layout: 'bubble', icons: 'bubbly', motion: 'bouncy', pattern: 'none', dark: false, accent: '#e88a9a' },
  clovercore: { font: 'Comfortaa', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'bubbly', motion: 'float', pattern: 'sparkles', dark: false, accent: '#4fae4f' },
  cluttercore: { font: 'Caveat', body: 'Lora', buttons: 'paper', layout: 'zine', icons: 'hand', motion: 'wobble', pattern: 'grain', dark: true, accent: '#e0a040' },
  'coastal-style': { font: 'Fraunces', body: 'Work Sans', buttons: 'outline', layout: 'classic', icons: 'line', motion: 'float', pattern: 'stripes', dark: false, accent: '#3f7fae' },
  'colorful-pop': { font: 'Potta One', body: 'Nunito', buttons: 'bubbly', layout: 'zine', icons: 'bubbly', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#ff2e9a' },
  'corporate-grunge': { font: 'Special Elite', body: 'Work Sans', buttons: 'sharp', layout: 'zine', icons: 'hand', motion: 'glitch', pattern: 'grain', dark: true, accent: '#d8342a' },
  'corporate-hippie': { font: 'Shrikhand', body: 'Lora', buttons: 'retro', layout: 'magazine', icons: 'hand', motion: 'wobble', pattern: 'squiggle', dark: false, accent: '#e8682a' },
  'corporate-memphis': { font: 'Unbounded', body: 'Work Sans', buttons: 'soft', layout: 'grid', icons: 'geometric', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#3d5afe' },
  'cozy-gamer': { font: 'Fredoka', body: 'Nunito', buttons: 'bubbly', layout: 'window', icons: 'bubbly', motion: 'float', pattern: 'sparkles', dark: true, accent: '#f5a7c0' },
  craftcore: { font: 'Caveat', body: 'Nunito', buttons: 'paper', layout: 'zine', icons: 'hand', motion: 'wobble', pattern: 'stitch', dark: false },
  'curly-girly': { font: 'Bubblegum Sans', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'bubbly', motion: 'bouncy', pattern: 'sparkles', dark: false, accent: '#ff3fa0' },
  cutecore: { font: 'Mochiy Pop One', body: 'Nunito', buttons: 'bubbly', layout: 'bubble', icons: 'bubbly', motion: 'bouncy', pattern: 'hearts', dark: false, accent: '#ff7fb0' },
  cyberminimalism: { font: 'Space Grotesk', body: 'Work Sans', buttons: 'outline', layout: 'top-tabs', icons: 'line', motion: 'snappy', pattern: 'grid', dark: false, accent: '#3045ff' },
  cybersigilism: { font: 'Pirata One', body: 'Work Sans', buttons: 'sharp', layout: 'centered', icons: 'line', motion: 'glitch', pattern: 'stars', dark: true, accent: '#e8ecf2' },
  'czech-cubism': { font: 'Syne', body: 'Work Sans', buttons: 'sharp', layout: 'framed', icons: 'geometric', motion: 'snappy', pattern: 'facets', dark: false, accent: '#c48a2a', caps: true },
  'danish-pastel': { font: 'Fraunces', body: 'Nunito', buttons: 'bubbly', layout: 'grid', icons: 'bubbly', motion: 'float', pattern: 'checker', dark: false, accent: '#d08ab5' },
  'dark-aero': { font: 'Audiowide', body: 'system', buttons: 'glossy', layout: 'window', icons: 'chrome', motion: 'float', pattern: 'haze', dark: true, accent: '#39e75f' },
  decoplex: { font: 'Federo', body: 'Work Sans', buttons: 'neon', layout: 'centered', icons: 'neon', motion: 'elegant', pattern: 'fans', dark: true, accent: '#29d3ff', caps: true },
  'disco-deco': { font: 'Monoton', body: 'Nunito', buttons: 'retro', layout: 'centered', icons: 'geometric', motion: 'bouncy', pattern: 'rays', dark: false, accent: '#f2552c' },
  'diy-punk': { font: 'Rubik Dirt', body: 'system', buttons: 'paper', layout: 'zine', icons: 'hand', motion: 'snappy', pattern: 'halftone', dark: false, accent: '#d7263d', caps: true, paper: true },
  'dollar-store-vernacular': { font: 'Bowlby One SC', body: 'system', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'wobble', pattern: 'halftone', dark: false, accent: '#ff2d20' },
  dorfic: { font: 'Comfortaa', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'bubbly', motion: 'float', pattern: 'bubbles', dark: false, accent: '#ff7a00' },
  'dunhuang-feng': { font: 'Ma Shan Zheng', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'float', pattern: 'waves', dark: false, accent: '#2e8b8b' },
  'early-cyber': { font: 'VT323', body: 'IBM Plex Mono', buttons: 'sharp', layout: 'terminal', icons: 'pixel', motion: 'stepped', pattern: 'scanlines', dark: true, accent: '#4f8bff' },
  'earth-tones': { font: 'Caprasimo', body: 'Lora', buttons: 'soft', layout: 'classic', icons: 'geometric', motion: 'smooth', pattern: 'stripes', dark: false, accent: '#e0701e' },
  'eco-beige': { font: 'Italiana', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'elegant', pattern: 'grain', dark: false, accent: '#8a6d4f' },
  'empire-style': { font: 'Cinzel', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'elegant', pattern: 'damask', dark: false, accent: '#a8843a', caps: true },
  'ethno-chic': { font: 'DM Serif Display', body: 'Lora', buttons: 'soft', layout: 'grid', icons: 'hand', motion: 'smooth', pattern: 'stitch', dark: false, accent: '#9a4a2a' },
  'factory-pomo': { font: 'Archivo Black', body: 'Work Sans', buttons: 'retro', layout: 'framed', icons: 'geometric', motion: 'snappy', pattern: 'grid', dark: true, accent: '#ff4a3d', caps: true },
  'fairground-baroque': { font: 'Rye', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'float', pattern: 'bulbs', dark: true, accent: '#f2b134' },
  fantasy2k: { font: 'Cinzel', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'sparkles', dark: false, accent: '#b08a3a' },
  'festival-marketplace': { font: 'Alfa Slab One', body: 'Nunito', buttons: 'soft', layout: 'grid', icons: 'bold', motion: 'bouncy', pattern: 'stripes', dark: false, accent: '#e04e39' },
  fileteado: { font: 'Lobster', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'damask', dark: true, accent: '#e8b923' },
  'flat-design': { font: 'Rubik', body: 'Work Sans', buttons: 'soft', layout: 'grid', icons: 'duotone', motion: 'smooth', pattern: 'none', dark: false, accent: '#2a9d8f' },
  'fleischer-style': { font: 'Chewy', body: 'Nunito', buttons: 'retro', layout: 'framed', icons: 'bold', motion: 'bouncy', pattern: 'grain', dark: false, accent: '#1c1c1c' },
  'food-mascot-kitsch': { font: 'Lilita One', body: 'Nunito', buttons: 'retro', layout: 'grid', icons: 'bold', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#e8572a' },
  'four-colors': { font: 'Inter Tight', body: 'Work Sans', buttons: 'soft', layout: 'floating', icons: 'line', motion: 'bouncy', pattern: 'none', dark: false, accent: '#ff2d8f' },
  frasurbane: { font: 'DM Serif Display', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'elegant', pattern: 'lines', dark: true, accent: '#c8955a' },
  'french-provincial-style': { font: 'Cormorant Garamond', body: 'Lora', buttons: 'outline', layout: 'centered', icons: 'line', motion: 'elegant', pattern: 'damask', dark: false, accent: '#8a7fbf' },
  'frutiger-aero': { font: 'Comfortaa', body: 'Nunito', buttons: 'glossy', layout: 'window', icons: 'bubbly', motion: 'float', pattern: 'bubbles', dark: false, accent: '#1e90ff' },
  'frutiger-eco': { font: 'Varela Round', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'bubbly', motion: 'float', pattern: 'waves', dark: false, accent: '#4caf1a' },
  'funfair-kitsch': { font: 'Bungee', body: 'system', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'bouncy', pattern: 'stars', dark: true, accent: '#ff3d7f', caps: true },
  'gay-nineties-revival': { font: 'Sancreek', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'stripes', dark: true, accent: '#e0a040' },
  'gen-z-maximalism': { font: 'Unbounded', body: 'Nunito', buttons: 'bubbly', layout: 'grid', icons: 'bubbly', motion: 'bouncy', pattern: 'checker', dark: false, accent: '#ff6a1a' },
  genericana: { font: 'Alfa Slab One', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'smooth', pattern: 'grain', dark: false, accent: '#c8352a' },
  'geo-boho': { font: 'Fraunces', body: 'Nunito', buttons: 'soft', layout: 'classic', icons: 'geometric', motion: 'smooth', pattern: 'arches', dark: false, accent: '#b5653a' },
  glassmorphism: { font: 'Sora', body: 'Work Sans', buttons: 'glass', layout: 'floating', icons: 'line', motion: 'float', pattern: 'haze', dark: false, accent: '#4a6cff' },
  'global-village-coffeehouse': { font: 'Shrikhand', body: 'Nunito', buttons: 'soft', layout: 'zine', icons: 'hand', motion: 'wobble', pattern: 'waves', dark: true, accent: '#f28c28' },
  'googie-kitsch': { font: 'Pacifico', body: 'Nunito', buttons: 'retro', layout: 'floating', icons: 'geometric', motion: 'bouncy', pattern: 'stars', dark: false, accent: '#ff7a59' },
  'graffiti-pop': { font: 'Rubik Spray Paint', body: 'system', buttons: 'retro', layout: 'zine', icons: 'hand', motion: 'wobble', pattern: 'squiggle', dark: true, accent: '#ff5a1f', caps: true },
  grandmillennial: { font: 'Playfair Display', body: 'Lora', buttons: 'outline', layout: 'classic', icons: 'line', motion: 'elegant', pattern: 'gingham', dark: false, accent: '#2f5d9e' },
  'grocery-girl-fall': { font: 'Fraunces', body: 'Nunito', buttons: 'soft', layout: 'grid', icons: 'hand', motion: 'smooth', pattern: 'gingham', dark: false, accent: '#e04a5a' },
  groovival: { font: 'Shrikhand', body: 'Nunito', buttons: 'bubbly', layout: 'bubble', icons: 'bubbly', motion: 'wobble', pattern: 'rays', dark: false, accent: '#f26b1d' },
  guochao: { font: 'ZCOOL QingKe HuangYou', body: 'system', buttons: 'sharp', layout: 'grid', icons: 'geometric', motion: 'snappy', pattern: 'lattice', dark: false, accent: '#d4232b' },
  gustavian: { font: 'Cormorant Garamond', body: 'Lora', buttons: 'outline', layout: 'centered', icons: 'line', motion: 'elegant', pattern: 'stripes', dark: false, accent: '#5f7f96' },
  'hands-up': { font: 'Audiowide', body: 'system', buttons: 'chrome', layout: 'magazine', icons: 'neon', motion: 'bouncy', pattern: 'rays', dark: true, accent: '#ff38c7', caps: true },
  'heroic-realism': { font: 'Anton', body: 'Work Sans', buttons: 'sharp', layout: 'magazine', icons: 'bold', motion: 'snappy', pattern: 'rays', dark: true, accent: '#d8342a', caps: true },
  'hipness-purgatory': { font: 'Special Elite', body: 'Lora', buttons: 'paper', layout: 'zine', icons: 'hand', motion: 'wobble', pattern: 'grain', dark: false, accent: '#d89a12' },
  'hollywood-regency': { font: 'Gilda Display', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'elegant', pattern: 'checker', dark: false, accent: '#b8902f' },
  hygge: { font: 'Fraunces', body: 'Lora', buttons: 'soft', layout: 'classic', icons: 'hand', motion: 'float', pattern: 'grain', dark: true, accent: '#e3a35f' },
  'industrial-gothic': { font: 'Pirata One', body: 'Work Sans', buttons: 'sharp', layout: 'framed', icons: 'line', motion: 'snappy', pattern: 'grid', dark: true, accent: '#c0662f' },
  'international-typographic-style': { font: 'Archivo Black', body: 'Work Sans', buttons: 'sharp', layout: 'magazine', icons: 'geometric', motion: 'snappy', pattern: 'grid', dark: false, accent: '#e3261b' },
  'italo-disco': { font: 'Tilt Neon', body: 'system', buttons: 'glossy', layout: 'floating', icons: 'neon', motion: 'float', pattern: 'lines', dark: true, accent: '#ff4fa3' },
  japandi: { font: 'Shippori Mincho', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'elegant', pattern: 'grain', dark: false, accent: '#6b5a45' },
  'jiggy-era': { font: 'Bungee', body: 'system', buttons: 'holo', layout: 'floating', icons: 'chrome', motion: 'bouncy', pattern: 'sparkles', dark: true, accent: '#ffd400', caps: true },
  'kid-science': { font: 'Baloo 2', body: 'Nunito', buttons: 'bubbly', layout: 'grid', icons: 'bubbly', motion: 'bouncy', pattern: 'bubbles', dark: false, accent: '#23b26d' },
  'laser-grid': { font: 'Orbitron', body: 'system', buttons: 'neon', layout: 'magazine', icons: 'neon', motion: 'float', pattern: 'horizon', dark: true, accent: '#ff3ec9', caps: true },
  'ligne-claire': { font: 'Patrick Hand SC', body: 'Nunito', buttons: 'outline', layout: 'framed', icons: 'line', motion: 'snappy', pattern: 'none', dark: false, accent: '#2f6db3' },
  'live-laugh-love': { font: 'Dancing Script', body: 'Lora', buttons: 'soft', layout: 'centered', icons: 'hand', motion: 'float', pattern: 'hearts', dark: false, accent: '#e07a9a' },
  mallsoft: { font: 'Syncopate', body: 'system', buttons: 'glossy', layout: 'window', icons: 'chrome', motion: 'float', pattern: 'checker', dark: true, accent: '#ff7ad9', caps: true },
  manguebeat: { font: 'Rubik Mono One', body: 'system', buttons: 'retro', layout: 'zine', icons: 'hand', motion: 'wobble', pattern: 'stripes', dark: false, accent: '#ff6a00', caps: true },
  maximalism: { font: 'Abril Fatface', body: 'Lora', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#e0306a' },
  medievalcore: { font: 'MedievalSharp', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'grain', dark: true, accent: '#c49a3a' },
  'memphis-design': { font: 'Bungee', body: 'Work Sans', buttons: 'retro', layout: 'grid', icons: 'geometric', motion: 'bouncy', pattern: 'squiggle', dark: false, accent: '#ff3e8a', caps: true },
  'memphis-jr': { font: 'Lilita One', body: 'Nunito', buttons: 'retro', layout: 'bubble', icons: 'geometric', motion: 'bouncy', pattern: 'checker', dark: false, accent: '#2952e3' },
  'memphis-lite': { font: 'Righteous', body: 'Work Sans', buttons: 'retro', layout: 'floating', icons: 'geometric', motion: 'smooth', pattern: 'squiggle', dark: false, accent: '#e05d9f' },
  metalheart: { font: 'Zen Dots', body: 'system', buttons: 'chrome', layout: 'centered', icons: 'chrome', motion: 'glitch', pattern: 'rays', dark: true, accent: '#57c7ff', caps: true },
  'mid-century-medieval': { font: 'Uncial Antiqua', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'smooth', pattern: 'lattice', dark: false, accent: '#c2422a' },
  'mid-century-modern': { font: 'Jost', body: 'Work Sans', buttons: 'soft', layout: 'classic', icons: 'geometric', motion: 'smooth', pattern: 'lines', dark: false, accent: '#e07b2a' },
  'mid-century-nursery-kitsch': { font: 'Sniglet', body: 'Nunito', buttons: 'bubbly', layout: 'bubble', icons: 'bubbly', motion: 'float', pattern: 'hearts', dark: false, accent: '#e889a8' },
  'mission-school': { font: 'Gochi Hand', body: 'Nunito', buttons: 'paper', layout: 'zine', icons: 'hand', motion: 'wobble', pattern: 'grain', dark: false, accent: '#e2583e' },
  modernisme: { font: 'Marcellus', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'mosaic', dark: false, accent: '#3d8ca0' },
  'monochrome-luxe': { font: 'Bodoni Moda', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'elegant', pattern: 'checker', dark: false, accent: '#1c1c1c', caps: true },
  nautical: { font: 'Alfa Slab One', body: 'Lora', buttons: 'retro', layout: 'classic', icons: 'line', motion: 'float', pattern: 'stripes', dark: false, accent: '#1f3a68' },
  'neo-chinese-style': { font: 'ZCOOL XiaoWei', body: 'Lora', buttons: 'outline', layout: 'centered', icons: 'line', motion: 'elegant', pattern: 'lattice', dark: false, accent: '#1f6f78' },
  'neo-vectorheart': { font: 'Turret Road', body: 'system', buttons: 'sharp', layout: 'magazine', icons: 'geometric', motion: 'glitch', pattern: 'lines', dark: false, accent: '#ff2f6d', caps: true },
  'neon-ooze': { font: 'Creepster', body: 'system', buttons: 'neon', layout: 'floating', icons: 'neon', motion: 'float', pattern: 'haze', dark: true, accent: '#8cff3a' },
  neubrutalism: { font: 'Archivo Black', body: 'Work Sans', buttons: 'retro', layout: 'grid', icons: 'bold', motion: 'snappy', pattern: 'grid', dark: false, accent: '#ff5aa5' },
  neumorphism: { font: 'Lexend', body: 'Nunito', buttons: 'neu', layout: 'classic', icons: 'line', motion: 'smooth', pattern: 'none', dark: false, accent: '#3fb8a8' },
  'new-ugly': { font: 'Comic Neue', body: 'system', buttons: 'sharp', layout: 'zine', icons: 'hand', motion: 'glitch', pattern: 'grain', dark: false, accent: '#2a3bff' },
  'new-wave': { font: 'Rubik Glitch', body: 'Work Sans', buttons: 'sharp', layout: 'magazine', icons: 'bold', motion: 'glitch', pattern: 'scanlines', dark: true, accent: '#ff3048', caps: true },
  'new-wave-tropical': { font: 'Kaushan Script', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'neon', motion: 'float', pattern: 'waves', dark: true, accent: '#26d0ce' },
  ostalgie: { font: 'Oswald', body: 'Work Sans', buttons: 'sharp', layout: 'top-tabs', icons: 'line', motion: 'snappy', pattern: 'grain', dark: false, accent: '#b5462a', caps: true },
  'pacific-punk-wave': { font: 'Bungee Inline', body: 'system', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'wobble', pattern: 'waves', dark: true, accent: '#ff2fa0', caps: true },
  'paperback-chic': { font: 'Fraunces', body: 'Nunito', buttons: 'soft', layout: 'grid', icons: 'duotone', motion: 'bouncy', pattern: 'none', dark: false, accent: '#0f8f7a' },
  'parisian-girly': { font: 'Great Vibes', body: 'Lora', buttons: 'soft', layout: 'centered', icons: 'hand', motion: 'float', pattern: 'stripes', dark: false, accent: '#f0287f' },
  'pc-98': { font: 'DotGothic16', body: 'IBM Plex Mono', buttons: 'pixel', layout: 'window', icons: 'pixel', motion: 'stepped', pattern: 'dither', dark: true, accent: '#8f7bff' },
  'pen-pixel': { font: 'Black Ops One', body: 'system', buttons: 'chrome', layout: 'magazine', icons: 'chrome', motion: 'bouncy', pattern: 'sparkles', dark: true, accent: '#e2b13c' },
  'photo-playground': { font: 'Chango', body: 'Nunito', buttons: 'bubbly', layout: 'window', icons: 'bubbly', motion: 'bouncy', pattern: 'stars', dark: false, accent: '#ff4a2a' },
  plakatstil: { font: 'Rammetto One', body: 'Work Sans', buttons: 'sharp', layout: 'magazine', icons: 'bold', motion: 'snappy', pattern: 'grain', dark: false, accent: '#e05a1a' },
  'polish-poster-school': { font: 'Big Shoulders Display', body: 'Work Sans', buttons: 'sharp', layout: 'framed', icons: 'hand', motion: 'snappy', pattern: 'grain', dark: false, accent: '#d7261e', caps: true },
  polychrome: { font: 'Bricolage Grotesque', body: 'Work Sans', buttons: 'holo', layout: 'floating', icons: 'duotone', motion: 'float', pattern: 'haze', dark: false, accent: '#7b5cff' },
  'positivity-kawaii': { font: 'Gaegu', body: 'Nunito', buttons: 'bubbly', layout: 'bubble', icons: 'hand', motion: 'bouncy', pattern: 'sparkles', dark: false, accent: '#ff8fb1' },
  'poster-gal': { font: 'Mochiy Pop P One', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'bubbly', motion: 'float', pattern: 'sparkles', dark: false, accent: '#b04adf' },
  'pulp-fantasy': { font: 'Metal Mania', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'smooth', pattern: 'grain', dark: true, accent: '#d8442a' },
  puppycore: { font: 'Mali', body: 'Nunito', buttons: 'bubbly', layout: 'bubble', icons: 'bubbly', motion: 'bouncy', pattern: 'hearts', dark: false, accent: '#7fb8ff' },
  'rad-dog': { font: 'Titan One', body: 'system', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'wobble', pattern: 'squiggle', dark: true, accent: '#b3ff3a' },
  'radical-design': { font: 'Syne', body: 'Work Sans', buttons: 'sharp', layout: 'zine', icons: 'geometric', motion: 'snappy', pattern: 'grid', dark: false, accent: '#e8402a', caps: true },
  'rainforest-chic': { font: 'Kavoon', body: 'Nunito', buttons: 'soft', layout: 'floating', icons: 'hand', motion: 'float', pattern: 'haze', dark: true, accent: '#f2a33a' },
  'raw-industrial': { font: 'Bebas Neue', body: 'Work Sans', buttons: 'sharp', layout: 'top-tabs', icons: 'line', motion: 'snappy', pattern: 'grid', dark: true, accent: '#d9822b' },
  'raygun-gothic': { font: 'Righteous', body: 'system', buttons: 'glossy', layout: 'floating', icons: 'chrome', motion: 'float', pattern: 'stars', dark: true, accent: '#ff8a2a' },
  'recession-pop': { font: 'Passion One', body: 'system', buttons: 'glossy', layout: 'zine', icons: 'bold', motion: 'bouncy', pattern: 'sparkles', dark: true, accent: '#ff3fa4' },
  'renaissance-revival': { font: 'IM Fell English', body: 'Lora', buttons: 'ornate', layout: 'framed', icons: 'ornate', motion: 'elegant', pattern: 'grain', dark: true, accent: '#c9842a' },
  'rgb-gamer': { font: 'Rajdhani', body: 'system', buttons: 'neon', layout: 'rail', icons: 'neon', motion: 'snappy', pattern: 'grid', dark: true, accent: '#a35bff', caps: true },
  'rocker-grrl-diva': { font: 'Rock Salt', body: 'system', buttons: 'sharp', layout: 'zine', icons: 'hand', motion: 'bouncy', pattern: 'sparkles', dark: true, accent: '#ff3f8e' },
  rococo: { font: 'Cormorant Upright', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'elegant', pattern: 'damask', dark: false, accent: '#d98aa3' },
  'scandinavian-design': { font: 'Manrope', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'geometric', motion: 'smooth', pattern: 'none', dark: false, accent: '#b5532e' },
  'seiz-breur': { font: 'Kumar One', body: 'Work Sans', buttons: 'sharp', layout: 'framed', icons: 'geometric', motion: 'snappy', pattern: 'zigzag', dark: false, accent: '#d8331f' },
  'sepia-blur': { font: 'EB Garamond', body: 'Lora', buttons: 'soft', layout: 'magazine', icons: 'line', motion: 'elegant', pattern: 'grain', dark: true, accent: '#d9a35c' },
  'shabby-chic': { font: 'Cormorant Infant', body: 'Lora', buttons: 'soft', layout: 'centered', icons: 'hand', motion: 'float', pattern: 'damask', dark: false, accent: '#c48390' },
  'shoe-diva': { font: 'Satisfy', body: 'Nunito', buttons: 'soft', layout: 'floating', icons: 'hand', motion: 'bouncy', pattern: 'stripes', dark: false, accent: '#e8467c' },
  'shuimo-feng': { font: 'Long Cang', body: 'Lora', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'elegant', pattern: 'haze', dark: false, accent: '#c0392b', paper: true },
  'silicon-dreams': { font: 'Exo 2', body: 'system', buttons: 'chrome', layout: 'window', icons: 'chrome', motion: 'float', pattern: 'checker', dark: true, accent: '#3fa9ff' },
  skeuomorphism: { font: 'Lobster', body: 'system', buttons: 'glossy', layout: 'classic', icons: 'chrome', motion: 'smooth', pattern: 'linen', dark: true, accent: '#4a90e2' },
  'soft-colonial-wanderlust': { font: 'IM Fell DW Pica', body: 'Lora', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'float', pattern: 'waves', dark: false, accent: '#6b7d4a' },
  'soft-countriana': { font: 'Calistoga', body: 'Lora', buttons: 'soft', layout: 'classic', icons: 'hand', motion: 'float', pattern: 'gingham', dark: false, accent: '#6b8fc0' },
  'soviet-chic': { font: 'Ruslan Display', body: 'Work Sans', buttons: 'sharp', layout: 'framed', icons: 'geometric', motion: 'snappy', pattern: 'stripes', dark: false, accent: '#c81e1e', caps: true },
  'space-age': { font: 'Michroma', body: 'system', buttons: 'glossy', layout: 'floating', icons: 'geometric', motion: 'float', pattern: 'stars', dark: false, accent: '#f26b1d', caps: true },
  sportsbrut: { font: 'Teko', body: 'Work Sans', buttons: 'sharp', layout: 'magazine', icons: 'bold', motion: 'snappy', pattern: 'lines', dark: true, accent: '#e8344a', caps: true },
  'streamline-moderne': { font: 'Poiret One', body: 'Lora', buttons: 'chrome', layout: 'centered', icons: 'line', motion: 'smooth', pattern: 'lines', dark: false, accent: '#3e8f8a' },
  'superflat-pop': { font: 'Dela Gothic One', body: 'Nunito', buttons: 'bubbly', layout: 'grid', icons: 'bubbly', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#ff3d8b' },
  'supergraphic-ultramodern': { font: 'Days One', body: 'Work Sans', buttons: 'soft', layout: 'magazine', icons: 'geometric', motion: 'smooth', pattern: 'stripes', dark: true, accent: '#ff8a3d' },
  teenpunk: { font: 'Permanent Marker', body: 'system', buttons: 'sharp', layout: 'zine', icons: 'hand', motion: 'glitch', pattern: 'grain', dark: true, accent: '#e8336f' },
  'themed-spaces': { font: 'Gluten', body: 'Nunito', buttons: 'bubbly', layout: 'bubble', icons: 'bubbly', motion: 'bouncy', pattern: 'confetti', dark: false, accent: '#e8232a' },
  'tranquil-serenity': { font: 'Quicksand', body: 'Nunito', buttons: 'soft', layout: 'centered', icons: 'line', motion: 'float', pattern: 'waves', dark: false, accent: '#cf3f8f' },
  trinketcore: { font: 'Chewy', body: 'Nunito', buttons: 'bubbly', layout: 'zine', icons: 'bubbly', motion: 'wobble', pattern: 'confetti', dark: false, accent: '#ff6b8b' },
  tropideco: { font: 'Chicle', body: 'Nunito', buttons: 'retro', layout: 'floating', icons: 'bold', motion: 'bouncy', pattern: 'waves', dark: true, accent: '#ff4f6d' },
  'tuscan-rustic': { font: 'Della Respira', body: 'Lora', buttons: 'soft', layout: 'framed', icons: 'hand', motion: 'smooth', pattern: 'lattice', dark: false, accent: '#a8562e' },
  urbling: { font: 'Saira Stencil One', body: 'system', buttons: 'sharp', layout: 'zine', icons: 'bold', motion: 'glitch', pattern: 'rays', dark: true, accent: '#ff8a00', caps: true },
  'utopian-scholastic': { font: 'Fredoka', body: 'Nunito', buttons: 'glossy', layout: 'window', icons: 'bubbly', motion: 'float', pattern: 'stars', dark: false, accent: '#1f7ae0' },
  'vector-minimalism': { font: 'Urbanist', body: 'Work Sans', buttons: 'outline', layout: 'magazine', icons: 'line', motion: 'smooth', pattern: 'none', dark: false, accent: '#e4572e' },
  'vector-musica': { font: 'Baumans', body: 'system', buttons: 'outline', layout: 'classic', icons: 'line', motion: 'bouncy', pattern: 'lines', dark: false, accent: '#8a3dff' },
  vectorbloom: { font: 'Courgette', body: 'Nunito', buttons: 'glossy', layout: 'floating', icons: 'hand', motion: 'float', pattern: 'sparkles', dark: false, accent: '#e8468a' },
  vectordelia: { font: 'Bungee', body: 'system', buttons: 'glossy', layout: 'zine', icons: 'bold', motion: 'bouncy', pattern: 'bubbles', dark: false, accent: '#8ccf1a' },
  'wacky-pomo': { font: 'Luckiest Guy', body: 'Nunito', buttons: 'retro', layout: 'zine', icons: 'bold', motion: 'wobble', pattern: 'squiggle', dark: true, accent: '#ffd21f' },
  whimsigothic: { font: 'Almendra', body: 'Lora', buttons: 'ornate', layout: 'centered', icons: 'ornate', motion: 'float', pattern: 'stars', dark: true, accent: '#b88ce6' },
  'y2k-futurism': { font: 'Tektur', body: 'system', buttons: 'chrome', layout: 'window', icons: 'chrome', motion: 'float', pattern: 'grid', dark: false, accent: '#2f6bff', caps: true },
  'yanqing-kitsch': { font: 'ZCOOL KuaiLe', body: 'Nunito', buttons: 'soft', layout: 'floating', icons: 'hand', motion: 'float', pattern: 'sparkles', dark: false, accent: '#d8607a' },
}
