// Hand-picked type and button style per aesthetic (colours come from its images).
// [display font, body font, button style, force dark (true) / light (false), accent]
// The accent is only set where the images' own colours miss the aesthetic's signature colour.
// Fonts are Google Fonts listed in src/lib/theme.ts. Body: system, Lora, Nunito,
// Work Sans, IBM Plex Mono. Buttons: soft, glossy, sharp, retro, ornate, outline, bubbly.

export const STYLES = {
  '2000s-modern-baroque': ['Playfair Display', 'Lora', 'ornate', true],
  '2010s-meme-maximalism': ['Bungee', 'system', 'retro'],
  '8-bit': ['Silkscreen', 'IBM Plex Mono', 'retro', true],
  '80s-90s-afrocentrism': ['Righteous', 'Nunito', 'soft'],
  'acid-design': ['Unbounded', 'Work Sans', 'sharp', true, '#b6ff3b'],
  'american-kitsch': ['Chewy', 'Nunito', 'retro'],
  'art-deco': ['Limelight', 'Lora', 'ornate', true, '#c9a227'],
  'art-nouveau': ['Cormorant Garamond', 'Lora', 'ornate'],
  'arts-and-crafts': ['Cormorant Garamond', 'Lora', 'outline', undefined, '#6b7a3a'],
  'atomic-age': ['Righteous', 'Nunito', 'retro', false, '#24a0a0'],
  austurbane: ['Space Grotesk', 'Work Sans', 'outline'],
  'avant-basic': ['Fraunces', 'Nunito', 'bubbly', false],
  avantropop: ['Audiowide', 'system', 'glossy'],
  baroque: ['Playfair Display', 'Lora', 'ornate', true, '#c59a3c'],
  biedermeier: ['Cormorant Garamond', 'Lora', 'outline', false, '#a8743f'],
  'big-pop': ['Bungee', 'system', 'retro', undefined, '#e6007e'],
  'blob-world': ['Fredoka', 'Nunito', 'bubbly'],
  'bootleg-aesthetic': ['Bowlby One SC', 'system', 'retro'],
  'bootleg-mixtape': ['Permanent Marker', 'system', 'sharp', true],
  'bright-tertiaries': ['Righteous', 'Nunito', 'soft'],
  'british-countryside': ['Playfair Display', 'Lora', 'outline', undefined, '#3f5f45'],
  'candy-sleaze': ['Fredoka', 'Nunito', 'bubbly'],
  'carson-dellosa-art-style': ['Baloo 2', 'Nunito', 'bubbly'],
  'catholic-kitsch': ['Cinzel', 'Lora', 'ornate'],
  chicha: ['Bungee', 'system', 'retro'],
  chromecore: ['Michroma', 'system', 'glossy', undefined, '#7f95ad'],
  claymorphism: ['Fredoka', 'Nunito', 'bubbly', false],
  clovercore: ['Comfortaa', 'Nunito', 'glossy'],
  cluttercore: ['Caveat', 'Nunito', 'soft'],
  'coastal-style': ['Fraunces', 'Nunito', 'outline', false, '#3f7fae'],
  'colorful-pop': ['Fredoka', 'Nunito', 'bubbly', undefined, '#ff4f9a'],
  'corporate-grunge': ['Archivo Black', 'Work Sans', 'sharp'],
  'corporate-hippie': ['Shrikhand', 'Nunito', 'soft'],
  'corporate-memphis': ['Unbounded', 'Work Sans', 'soft', false],
  'cozy-gamer': ['Fredoka', 'Nunito', 'bubbly', undefined, '#a77ad0'],
  craftcore: ['Caveat', 'Nunito', 'soft'],
  'curly-girly': ['Pacifico', 'Nunito', 'bubbly'],
  cutecore: ['Fredoka', 'Nunito', 'bubbly', undefined, '#ec7fae'],
  cyberminimalism: ['Space Grotesk', 'Work Sans', 'outline'],
  cybersigilism: ['Pirata One', 'Work Sans', 'sharp', true, '#c9d1d9'],
  'czech-cubism': ['Syne', 'Work Sans', 'sharp'],
  'danish-pastel': ['Fraunces', 'Nunito', 'bubbly', false, '#d08ab5'],
  'dark-aero': ['Audiowide', 'system', 'glossy', true, '#37c6d0'],
  decoplex: ['Limelight', 'system', 'ornate', true],
  'disco-deco': ['Righteous', 'system', 'glossy', true],
  'diy-punk': ['Permanent Marker', 'IBM Plex Mono', 'sharp'],
  'dollar-store-vernacular': ['Bowlby One SC', 'system', 'retro'],
  dorfic: ['Space Grotesk', 'Work Sans', 'outline'],
  'dunhuang-feng': ['ZCOOL XiaoWei', 'Lora', 'ornate'],
  'early-cyber': ['VT323', 'IBM Plex Mono', 'sharp', true],
  'earth-tones': ['Fraunces', 'Lora', 'soft'],
  'eco-beige': ['Fraunces', 'Nunito', 'outline', false],
  'empire-style': ['Cinzel', 'Lora', 'ornate'],
  'ethno-chic': ['Fraunces', 'Lora', 'soft'],
  'factory-pomo': ['Archivo Black', 'Work Sans', 'retro'],
  'fairground-baroque': ['Alfa Slab One', 'Lora', 'ornate'],
  fantasy2k: ['Cinzel', 'Lora', 'glossy', true, '#b38cff'],
  'festival-marketplace': ['Righteous', 'Nunito', 'soft'],
  fileteado: ['Lobster', 'Lora', 'ornate', true, '#e8b923'],
  'flat-design': ['Space Grotesk', 'Work Sans', 'outline', false],
  'fleischer-style': ['Chewy', 'Nunito', 'retro'],
  'food-mascot-kitsch': ['Chewy', 'Nunito', 'retro'],
  'four-colors': ['Comfortaa', 'Nunito', 'glossy'],
  frasurbane: ['DM Serif Display', 'Work Sans', 'outline'],
  'french-provincial-style': ['Cormorant Garamond', 'Lora', 'outline', false, '#6f7fae'],
  'frutiger-aero': ['Comfortaa', 'Nunito', 'glossy', false],
  'frutiger-eco': ['Comfortaa', 'Nunito', 'glossy', false],
  'funfair-kitsch': ['Alfa Slab One', 'Nunito', 'retro'],
  'gay-nineties-revival': ['Abril Fatface', 'Lora', 'ornate'],
  'gen-z-maximalism': ['Unbounded', 'Nunito', 'bubbly'],
  genericana: ['Fraunces', 'Work Sans', 'outline'],
  'geo-boho': ['Fraunces', 'Nunito', 'outline', false],
  glassmorphism: ['Space Grotesk', 'Work Sans', 'glossy'],
  'global-village-coffeehouse': ['Fraunces', 'Nunito', 'soft'],
  'googie-kitsch': ['Pacifico', 'Nunito', 'retro'],
  'graffiti-pop': ['Permanent Marker', 'system', 'retro'],
  grandmillennial: ['Playfair Display', 'Lora', 'outline', false],
  'grocery-girl-fall': ['Fraunces', 'Nunito', 'bubbly', false],
  groovival: ['Shrikhand', 'Nunito', 'soft'],
  guochao: ['ZCOOL XiaoWei', 'system', 'sharp'],
  gustavian: ['Cormorant Garamond', 'Lora', 'outline', false, '#5f7f96'],
  'hands-up': ['Audiowide', 'system', 'glossy', true],
  'heroic-realism': ['Archivo Black', 'Work Sans', 'sharp'],
  'hipness-purgatory': ['Special Elite', 'Lora', 'outline'],
  'hollywood-regency': ['DM Serif Display', 'Lora', 'ornate', undefined, '#b8902f'],
  hygge: ['Fraunces', 'Lora', 'soft', false],
  'industrial-gothic': ['Pirata One', 'Lora', 'sharp', true, '#b33a3a'],
  'international-typographic-style': ['Archivo Black', 'Work Sans', 'sharp', false],
  'italo-disco': ['Monoton', 'system', 'glossy', true, '#ff4fa3'],
  japandi: ['Cormorant Garamond', 'Work Sans', 'outline', false],
  'jiggy-era': ['Michroma', 'system', 'glossy', true, '#d4af37'],
  'kid-science': ['Baloo 2', 'Nunito', 'bubbly'],
  'laser-grid': ['Tilt Neon', 'system', 'glossy', true, '#ff3ec9'],
  'ligne-claire': ['Archivo Black', 'Nunito', 'outline', false],
  'live-laugh-love': ['Caveat', 'Lora', 'soft', false],
  mallsoft: ['Tilt Neon', 'system', 'glossy'],
  manguebeat: ['Permanent Marker', 'system', 'retro'],
  maximalism: ['Abril Fatface', 'Lora', 'ornate'],
  medievalcore: ['Pirata One', 'Lora', 'ornate', undefined, '#4f6f3a'],
  'memphis-design': ['Bungee', 'Work Sans', 'retro', false],
  'memphis-jr': ['Baloo 2', 'Nunito', 'retro', false],
  'memphis-lite': ['Righteous', 'Work Sans', 'retro', false],
  metalheart: ['Michroma', 'system', 'glossy', true, '#4fb3ff'],
  'mid-century-medieval': ['Cinzel', 'Lora', 'ornate'],
  'mid-century-modern': ['Righteous', 'Nunito', 'soft'],
  'mid-century-nursery-kitsch': ['Chewy', 'Nunito', 'bubbly', false],
  'mission-school': ['Special Elite', 'Lora', 'sharp'],
  modernisme: ['Cormorant Garamond', 'Lora', 'ornate'],
  'monochrome-luxe': ['DM Serif Display', 'Work Sans', 'outline', undefined, '#2b2b2b'],
  nautical: ['Alfa Slab One', 'Lora', 'outline', false],
  'neo-chinese-style': ['ZCOOL XiaoWei', 'Lora', 'outline'],
  'neo-vectorheart': ['Audiowide', 'system', 'glossy'],
  'neon-ooze': ['Bungee', 'system', 'retro', true, '#8cff3a'],
  neubrutalism: ['Archivo Black', 'Work Sans', 'retro', false],
  neumorphism: ['Comfortaa', 'Nunito', 'soft'],
  'new-ugly': ['Rubik Mono One', 'system', 'sharp'],
  'new-wave': ['Bungee', 'Work Sans', 'sharp'],
  'new-wave-tropical': ['Righteous', 'Nunito', 'retro'],
  ostalgie: ['Archivo Black', 'Work Sans', 'sharp'],
  'pacific-punk-wave': ['Bungee', 'system', 'retro'],
  'paperback-chic': ['Abril Fatface', 'Lora', 'outline'],
  'parisian-girly': ['Pacifico', 'Nunito', 'soft'],
  'pc-98': ['VT323', 'IBM Plex Mono', 'sharp', true],
  'pen-pixel': ['Michroma', 'system', 'glossy', true, '#e2b13c'],
  'photo-playground': ['Comfortaa', 'Nunito', 'glossy'],
  plakatstil: ['Alfa Slab One', 'Work Sans', 'sharp'],
  'polish-poster-school': ['Abril Fatface', 'Work Sans', 'sharp'],
  polychrome: ['Unbounded', 'Work Sans', 'soft'],
  'positivity-kawaii': ['Fredoka', 'Nunito', 'bubbly', false],
  'poster-gal': ['Fredoka', 'Nunito', 'glossy'],
  'pulp-fantasy': ['Alfa Slab One', 'Lora', 'ornate'],
  puppycore: ['Fredoka', 'Nunito', 'bubbly', false],
  'rad-dog': ['Bungee', 'system', 'retro'],
  'radical-design': ['Syne', 'Work Sans', 'sharp'],
  'rainforest-chic': ['Fraunces', 'Nunito', 'soft'],
  'raw-industrial': ['Archivo Black', 'Work Sans', 'sharp', true],
  'raygun-gothic': ['Orbitron', 'system', 'glossy'],
  'recession-pop': ['Audiowide', 'system', 'glossy', true, '#ff3fa4'],
  'renaissance-revival': ['Cinzel', 'Lora', 'ornate'],
  'rgb-gamer': ['Orbitron', 'system', 'sharp', true],
  'rocker-grrl-diva': ['Permanent Marker', 'system', 'sharp', true],
  rococo: ['Cormorant Garamond', 'Lora', 'ornate', false, '#d98aa3'],
  'scandinavian-design': ['Space Grotesk', 'Work Sans', 'outline', false],
  'seiz-breur': ['Poiret One', 'Lora', 'ornate'],
  'sepia-blur': ['Playfair Display', 'Lora', 'soft'],
  'shabby-chic': ['Cormorant Garamond', 'Lora', 'soft', false, '#c48390'],
  'shoe-diva': ['Pacifico', 'Nunito', 'bubbly'],
  'shuimo-feng': ['ZCOOL XiaoWei', 'Lora', 'outline', false],
  'silicon-dreams': ['Orbitron', 'system', 'glossy', true],
  skeuomorphism: ['Comfortaa', 'Nunito', 'glossy'],
  'soft-colonial-wanderlust': ['Cormorant Garamond', 'Lora', 'outline'],
  'soft-countriana': ['Fraunces', 'Lora', 'soft', false],
  'soviet-chic': ['Rubik Mono One', 'Work Sans', 'sharp'],
  'space-age': ['Orbitron', 'system', 'glossy'],
  sportsbrut: ['Bowlby One SC', 'Work Sans', 'sharp'],
  'streamline-moderne': ['Poiret One', 'Lora', 'ornate', undefined, '#3e8f8a'],
  'superflat-pop': ['Fredoka', 'Nunito', 'bubbly'],
  'supergraphic-ultramodern': ['Righteous', 'Work Sans', 'sharp'],
  teenpunk: ['Permanent Marker', 'system', 'retro'],
  'themed-spaces': ['Alfa Slab One', 'Nunito', 'retro'],
  'tranquil-serenity': ['Comfortaa', 'Nunito', 'glossy', false],
  trinketcore: ['Caveat', 'Nunito', 'bubbly'],
  tropideco: ['Righteous', 'Nunito', 'soft'],
  'tuscan-rustic': ['Cormorant Garamond', 'Lora', 'outline'],
  urbling: ['Permanent Marker', 'system', 'sharp', true],
  'utopian-scholastic': ['Baloo 2', 'Nunito', 'glossy', false],
  'vector-minimalism': ['Space Grotesk', 'Work Sans', 'outline', false],
  'vector-musica': ['Audiowide', 'system', 'glossy'],
  vectorbloom: ['Comfortaa', 'Nunito', 'glossy'],
  vectordelia: ['Unbounded', 'system', 'glossy'],
  'wacky-pomo': ['Bungee', 'Nunito', 'retro'],
  whimsigothic: ['Pirata One', 'Lora', 'ornate', true, '#9b6bb5'],
  'y2k-futurism': ['Michroma', 'system', 'glossy'],
  'yanqing-kitsch': ['ZCOOL XiaoWei', 'Lora', 'soft'],
}

/** For aesthetics added to the wiki later: a style guessed from the decade. */
export function fallbackStyle(year) {
  if (year === undefined) return ['Instrument Serif', 'system', 'soft']
  if (year < 1900) return ['Playfair Display', 'Lora', 'ornate']
  if (year < 1940) return ['Poiret One', 'Lora', 'ornate']
  if (year < 1960) return ['Righteous', 'Nunito', 'retro']
  if (year < 1980) return ['Shrikhand', 'Nunito', 'soft']
  if (year < 1995) return ['Bungee', 'system', 'retro']
  if (year < 2010) return ['Audiowide', 'system', 'glossy']
  return ['Space Grotesk', 'Work Sans', 'outline']
}
